import inventoryOne from '../assets/images/inventoryOne.png';
import inventoryTwo from '../assets/images/inventoryTwo.png';
import inventoryThree from '../assets/images/inventoryThree.png';
import inventoryFour from '../assets/images/inventoryFour.png';
import inventoryFive from '../assets/images/inventoryFive.png';
import verified from '../assets/images/verified.png';
import Amaka from '../assets/images/amaka.png';
import Jaz from '../assets/images/jaz.png';
import Nolitha from '../assets/images/nolitha.png';
import Olumide from '../assets/images/olumide.png';
import problemsome from '../assets/images/creator1.png'

export const inventoryNFT = [
    {
        name: "EarthStrike",
        image: inventoryOne,
        author: "Nolitha",
        price:  "2.5",
        rent: "1.0",
        status: "On Sale",
        likes: "100",
        profileStatus: verified,
        profileImage: Nolitha,
        about: "The EarthStrike is a remarkable weapon that combines eco-consciousness with formidable strength. Crafted from responsibly sourced materials and infused with nature's energy, this bat allows you to fight against enemies while championing a greener world. From the crack of its sustainable wood to the eco-friendly grip, the EarthStrike empowers you to defend the environment while battling adversaries."
    },
    {
        name: "GreenCycle",
        image: inventoryTwo,
        author: "Jaz",
        price:  "3.3",
        rent: "1.5",
        status: "On Sale",
        likes: "120",
        profileStatus: verified,
        profileImage: Jaz,
        about: "GreenCycle is a revolutionary two-wheeled marvel that runs on pure clean energy. Powered by an advanced electric propulsion system, this eco-friendly ride propels you forward with the sun's radiant power. With each UV exposure, the GreenCycle harnesses solar energy and converts it into a seamless and efficient ride. "
    },
    {
        name: "BioMotive",
        image: inventoryThree,
        author: "Amaka",
        price:  "2.2",
        rent: "1.5",
        status: "On Sale",
        likes: "150",
        profileStatus: verified,
        profileImage: Amaka,
        about: "BioMotive is an extraordinary electric car powered by advanced biofuel technology. BioMotive utilizes biofuels derived from renewable sources such as plant matter and organic waste. With each drive, you embark on a greener journey, knowing that its biofuel blend reduces greenhouse gas emissions and minimizes environmental impact. Its engine seamlessly converts biofuel into clean and efficient energy, delivering an eco-friendly driving experience."
    },
    {
        name: "AntTrail",
        image: inventoryFour,
        author: "Olumide",
        price:  "3.7",
        rent: "1.8",
        status: "On Sale",
        likes: "180",
        profileStatus: verified,
        profileImage: Olumide,
        about: "AntTrail, is an extraordinary two-wheeled marvel that takes its inspiration from the graceful and industrious ant. With its sleek and aerodynamic design, the AntTrail emulates the elegance and efficiency of its insect counterpart. The AntTrail boasts a lightweight frame constructed from advanced composite materials and harnesses the power of human motion and advanced kinetic energy recovery technology to convert the energy generated by pedaling into electricity.",
    },
    {
        name: "BeetleDrive",
        image: inventoryFive,
        author: "Problemsome",
        price:  "4.5",
        rent: "2.0",
        status: "On Sale",
        likes: "1000",
        profileStatus: verified,
        profileImage: problemsome,
        about: "BeetleDrive is an extraordinary car that draws inspiration from the iconic and resilient beetle. The BeetleDrive also incorporates sustainable and eco-friendly features. Powered by an advanced wind drivetrain, the BeetleDrive leaves behind zero emissions and operates silently, contributing to a cleaner and quieter environment"
    },
    {
        name: "EarthStrike",
        image: inventoryOne,
        author: "Nolitha",
        price:  "2.5",
        rent: "1.0",
        status: "On Sale",
        likes: "100",
        profileStatus: verified,
        profileImage: Nolitha,
        about: "The EarthStrike is a remarkable weapon that combines eco-consciousness with formidable strength. Crafted from responsibly sourced materials and infused with nature's energy, this bat allows you to fight against enemies while championing a greener world. From the crack of its sustainable wood to the eco-friendly grip, the EarthStrike empowers you to defend the environment while battling adversaries."
    },
    {
        name: "GreenCycle",
        image: inventoryTwo,
        author: "Jaz",
        price:  "3.3",
        rent: "1.5",
        status: "On Sale",
        likes: "120",
        profileStatus: verified,
        profileImage: Jaz,
        about: "GreenCycle is a revolutionary two-wheeled marvel that runs on pure clean energy. Powered by an advanced electric propulsion system, this eco-friendly ride propels you forward with the sun's radiant power. With each UV exposure, the GreenCycle harnesses solar energy and converts it into a seamless and efficient ride. "
    },
    {
        name: "BioMotive",
        image: inventoryThree,
        author: "Amaka",
        price:  "2.2",
        rent: "1.5",
        status: "On Sale",
        likes: "150",
        profileStatus: verified,
        profileImage: Amaka,
        about: "BioMotive is an extraordinary electric car powered by advanced biofuel technology. BioMotive utilizes biofuels derived from renewable sources such as plant matter and organic waste. With each drive, you embark on a greener journey, knowing that its biofuel blend reduces greenhouse gas emissions and minimizes environmental impact. Its engine seamlessly converts biofuel into clean and efficient energy, delivering an eco-friendly driving experience."
    },
]